name: pytest-multi-results-action
description: Post pytest results to the workflow summary

branding:
  icon: bookmark
  color: red

runs:
  using: node20
  main: dist/index.js

inputs:
  files:
    description: |
      Multiple JUnit XML file patterns for multi-suite aggregation.
      Each pattern can be a file, directory, or wildcard pattern.
      See @actions/glob for supported patterns.
    required: true
  title:
    description: Title of the test results section in the workflow summary
    required: false
    default: Test results
  summary:
    description: Add a summary of the results at the top of the report
    required: false
    default: true
  details:
    description: Add details section after the test results
    required: false
    default: true
  fail-on-empty:
    description: Fail the workflow if no JUnit XML was found
    required: false
    default: true
  metadata-fields:
    description: |
      Comma-separated list of metadata fields to extract from XML and display in tables.
      Supports pytest-metadata properties and custom XML attributes.
      If not provided, defaults to "Suite" column.
      Example: "artifact,type,namespace"
    required: false
    default: ""
  metadata-field-mapping:
    description: |
      JSON object mapping XML attribute/property names to display names.
      Example: '{"artifact": "Artifact", "type": "Type", "namespace": "Namespace"}'
    required: false
    default: "{}"
  result-types:
    description: |
      Comma-separated list of result types to include, in order.
      Allowed values: passed, skipped, xfailed, failed, xpassed, error
    required: false
    default: "passed,skipped,xfailed,failed,xpassed,error"
  details-result-types:
    description: |
      Comma-separated list of result types to include, in order.
      Allowed values: passed, skipped, xfailed, failed, xpassed, error
    required: false
    default: "failed,error"
